version: "3.7"
services:
  node:
    image: "node:17.8.0-stretch-slim"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000"
    command: "npm run start"