version: "3.7"
services:
  node:
    build: .
    user: "node"
    depends_on:
      - mysql-db
    # command: apk update; apk add -u bash; bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    volumes:
      - ./:/app
    # expose:
    #   - "8000"
    ports:
      - "8000:80"
    environment:
      NODE_ENV: development

  mysql-db:
    env_file:
      - ".env"
    build: db
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "8001:3306"
    restart: unless-stopped
